name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: dungeon-desk-486622
  SERVICE_NAME: dungeon-desk-back
  REGION: europe-west9

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Étape de test : Empêche le déploiement si les tests échouent
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './package-lock.json' # Spécifie le chemin si le package.json n'est pas à la racine

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      # Authentification via Google Cloud Service Account Key (JSON)
      # Il faudra ajouter ce secret dans GitHub
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker europe-west9-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        run: |
          docker build -t europe-west9-docker.pkg.dev/${{ env.PROJECT_ID }}/dungeon-desk-repo/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push europe-west9-docker.pkg.dev/${{ env.PROJECT_ID }}/dungeon-desk-repo/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          image: europe-west9-docker.pkg.dev/${{ env.PROJECT_ID }}/dungeon-desk-repo/${{ env.SERVICE_NAME }}:${{ github.sha }}

          region: ${{ env.REGION }}
          env_vars: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}
            AUTH0_ISSUER=${{ secrets.AUTH0_ISSUER }}
